.jobs_template: &test_definition
  image: 'ruby:2.4'
  stage: test
stages:
  - test
  - staging
  - deploy
services:
  - postgres:latest
test:
  variables:
    RAILS_ENV: test
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y nodejs
    - bundle install --path /cache
    - bundle exec rails db:create RAILS_ENV=test
rspec:
  <<: *deploy_definition
  script:
    - bundle exec rspec
rubocop:
  stage: test
  script:
    - bundle exec rubocop
#https://github.com/chetan/simplecov-console ( add gem )
brakeman:
  stage: test
  script:
    - bundle exec brakeman -z -q
rails-best-practices:
  stage: test
  script:
    - rails_best_practices .
.jobs_template: &deploy_definition
  image: tsuru/client
  stage: deploy
  environment:
    name: ${DEPLOY_MODE}
  variables:
    CI_PROJECT_NAME: test-app
  script:
    -  tsuru app-deploy -a ${CI_PROJECT_NAME}-${DEPLOY_MODE} Procfile tsuru.yaml
staging:
  <<: *deploy_definition
  only:
    - staging
  variables:
    DEPLOY_MODE: staging
production:
  <<: *deploy_definition
  only:
    - master
  when: manual
  variables:
    DEPLOY_MODE: production