default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: app_database
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default